### ISSUE TITLE
Score jumps from 1000 to 1400

### ISSUE THREAD

**Issue by Damjan94** [Ranger-NF/BlastOff#1]
`_calculate_score` uses elapsed time and current level to calculate the score
```
score_gained = roundi(current_level * time_spent)
```
But if time spent is 500 seconds, and current level goes from 2 to 3, the score jumps from 1000 to 1500

When I get the chance, if this is not fixed by then, I'll do something like this
```
var score_increment =  1 + current_level * 10(or any other magic value that "feels" right)

func _calculate_score() -> void:
    score_gained += score_increment

   ....
```

This would unfortunately change the current behavior that the score increases quicker as time goes on.

**Comment by FahadLive** [comment]
I had noticed it when the score went from 10 to 20 (level 1 to 2). But never thought it would affect on such a large scale...

Since I already completed 95% of v1.4.0. I will try fixing this issue sometime soon.... Thanks for bringing up the issue
